include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    avoid_print: warning
    invalid_use_of_visible_for_testing_member: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_super_parameters: true
